### ISSUE TITLE
biker parrot

### ISSUE THREAD

**Issue by justnance** [zer0db/staletest-01#10]
/md ![](https://cultofthepartyparrot.com/parrots/hd/bikerparrot.gif)

**Comment by justnance** [comment]
![](https://cultofthepartyparrot.com/parrots/hd/bikerparrot.gif)  ![](https://cultofthepartyparrot.com/parrots/hd/bikerparrot.gif)  ![](https://cultofthepartyparrot.com/parrots/hd/bikerparrot.gif)  ![](https://cultofthepartyparrot.com/parrots/hd/bikerparrot.gif)

**Comment by zer0db** [comment]
Closing but leaving for posterity.
